nodes:
  hosts:
    es01:
      ansible_user: "{{SSH_USER}}"
      ansible_host: 10.120.73.177
      ansible_ssh_private_key_file: "{{SSH_PRIVATE_KEY}}"

    es02:
      ansible_user: "{{SSH_USER}}"
      ansible_host: 10.120.73.166
      ansible_ssh_private_key_file: "{{SSH_PRIVATE_KEY}}"

    es03:
      ansible_user: "{{SSH_USER}}"
      ansible_host: 10.120.73.56
      ansible_ssh_private_key_file: "{{SSH_PRIVATE_KEY}}"
    
node_generate_cert_and_ca:
  hosts:
    es01:
      ansible_user: "{{SSH_USER}}"
      ansible_host: 10.120.73.177
      ansible_ssh_private_key_file: "{{SSH_PRIVATE_KEY}}"

vms:
  vars:
    # Define global variable
    SSH_USER: ubuntu
    SSH_PRIVATE_KEY: /home/vunv/.ssh/id_rsa

  children:
    node_generate_cert_and_ca:
    nodes:
