- name: Sudo apt update
  become: true
  hosts: vms
  tasks:

    - name: Run
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
